version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hackmate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hackmate_db
      MYSQL_USER: hackmate
      MYSQL_PASSWORD: hackmate123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - hackmate-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackmate-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hackmate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: hackmate
      SPRING_DATASOURCE_PASSWORD: hackmate123
      JWT_SECRET: mySecretKey
      JWT_EXPIRATION: 86400000
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hackmate-network
    volumes:
      - ./backend/logs:/app/logs

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackmate-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api
      REACT_APP_WS_BASE_URL: ws://localhost:8080/ws
    depends_on:
      - backend
    networks:
      - hackmate-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Redis for session management (optional)
  redis:
    image: redis:7-alpine
    container_name: hackmate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hackmate-network
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  hackmate-network:
    driver: bridge